### PR TITLE
Remove Net 7 Dependencies

### PR DESCRIPTION
**Pull request by javierpardollama**

### CODE REVIEW

**Comment by eltjo-k** [comment]
Dear @javierpardollama: thank  you for these changes. There is one thing missing and that is to increase the version numbers in the DotNet projects.

**Review by eltjo-k — CHANGES_REQUESTED** [review]
Please update the version numbers for defined in the dotnet projects as well.

**Comment by javierpardollama** [comment]
Done @eltjo-k! I do not know how that went through unnoticed...

**Review by Falasvido — APPROVED** [review]
Approved!

**Pull request merged**
